//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoClient.CryptoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CryptoService.ICryptoService")]
    public interface ICryptoService {
        
        // CODEGEN: Generating message contract since the wrapper name (FileDetails) of message FileDetails does not match the default value (Upload)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/Upload", ReplyAction="http://tempuri.org/ICryptoService/UploadResponse")]
        CryptoClient.CryptoService.UploadReply Upload(CryptoClient.CryptoService.FileDetails request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/Upload", ReplyAction="http://tempuri.org/ICryptoService/UploadResponse")]
        System.Threading.Tasks.Task<CryptoClient.CryptoService.UploadReply> UploadAsync(CryptoClient.CryptoService.FileDetails request);
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadFile) of message DownloadFile does not match the default value (LoadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/LoadFile", ReplyAction="http://tempuri.org/ICryptoService/LoadFileResponse")]
        CryptoClient.CryptoService.FileDetails LoadFile(CryptoClient.CryptoService.DownloadFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/LoadFile", ReplyAction="http://tempuri.org/ICryptoService/LoadFileResponse")]
        System.Threading.Tasks.Task<CryptoClient.CryptoService.FileDetails> LoadFileAsync(CryptoClient.CryptoService.DownloadFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/GetFilesNames", ReplyAction="http://tempuri.org/ICryptoService/GetFilesNamesResponse")]
        string[] GetFilesNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/GetFilesNames", ReplyAction="http://tempuri.org/ICryptoService/GetFilesNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetFilesNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/DeleteFile", ReplyAction="http://tempuri.org/ICryptoService/DeleteFileResponse")]
        bool DeleteFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICryptoService/DeleteFile", ReplyAction="http://tempuri.org/ICryptoService/DeleteFileResponse")]
        System.Threading.Tasks.Task<bool> DeleteFileAsync(string fileName);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileDetails {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileStreamReader;
        
        public FileDetails() {
        }
        
        public FileDetails(string FileName, System.IO.Stream FileStreamReader) {
            this.FileName = FileName;
            this.FileStreamReader = FileStreamReader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadReply", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadReply {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UploadSuccess;
        
        public UploadReply() {
        }
        
        public UploadReply(bool UploadSuccess) {
            this.UploadSuccess = UploadSuccess;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FileName;
        
        public DownloadFile() {
        }
        
        public DownloadFile(string FileName) {
            this.FileName = FileName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICryptoServiceChannel : CryptoClient.CryptoService.ICryptoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CryptoServiceClient : System.ServiceModel.ClientBase<CryptoClient.CryptoService.ICryptoService>, CryptoClient.CryptoService.ICryptoService {
        
        public CryptoServiceClient() {
        }
        
        public CryptoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CryptoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoClient.CryptoService.UploadReply CryptoClient.CryptoService.ICryptoService.Upload(CryptoClient.CryptoService.FileDetails request) {
            return base.Channel.Upload(request);
        }
        
        public bool Upload(string FileName, System.IO.Stream FileStreamReader) {
            CryptoClient.CryptoService.FileDetails inValue = new CryptoClient.CryptoService.FileDetails();
            inValue.FileName = FileName;
            inValue.FileStreamReader = FileStreamReader;
            CryptoClient.CryptoService.UploadReply retVal = ((CryptoClient.CryptoService.ICryptoService)(this)).Upload(inValue);
            return retVal.UploadSuccess;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoClient.CryptoService.UploadReply> CryptoClient.CryptoService.ICryptoService.UploadAsync(CryptoClient.CryptoService.FileDetails request) {
            return base.Channel.UploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoClient.CryptoService.UploadReply> UploadAsync(string FileName, System.IO.Stream FileStreamReader) {
            CryptoClient.CryptoService.FileDetails inValue = new CryptoClient.CryptoService.FileDetails();
            inValue.FileName = FileName;
            inValue.FileStreamReader = FileStreamReader;
            return ((CryptoClient.CryptoService.ICryptoService)(this)).UploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoClient.CryptoService.FileDetails CryptoClient.CryptoService.ICryptoService.LoadFile(CryptoClient.CryptoService.DownloadFile request) {
            return base.Channel.LoadFile(request);
        }
        
        public System.IO.Stream LoadFile(ref string FileName) {
            CryptoClient.CryptoService.DownloadFile inValue = new CryptoClient.CryptoService.DownloadFile();
            inValue.FileName = FileName;
            CryptoClient.CryptoService.FileDetails retVal = ((CryptoClient.CryptoService.ICryptoService)(this)).LoadFile(inValue);
            FileName = retVal.FileName;
            return retVal.FileStreamReader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoClient.CryptoService.FileDetails> CryptoClient.CryptoService.ICryptoService.LoadFileAsync(CryptoClient.CryptoService.DownloadFile request) {
            return base.Channel.LoadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoClient.CryptoService.FileDetails> LoadFileAsync(string FileName) {
            CryptoClient.CryptoService.DownloadFile inValue = new CryptoClient.CryptoService.DownloadFile();
            inValue.FileName = FileName;
            return ((CryptoClient.CryptoService.ICryptoService)(this)).LoadFileAsync(inValue);
        }
        
        public string[] GetFilesNames() {
            return base.Channel.GetFilesNames();
        }
        
        public System.Threading.Tasks.Task<string[]> GetFilesNamesAsync() {
            return base.Channel.GetFilesNamesAsync();
        }
        
        public bool DeleteFile(string fileName) {
            return base.Channel.DeleteFile(fileName);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFileAsync(string fileName) {
            return base.Channel.DeleteFileAsync(fileName);
        }
    }
}
